name: Sync Branches Manual
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Target Branch
        default: ''
        required: true

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> dev-${{github.event.inputs.branch}}
        uses: devmasx/merge-branch@v1.3.1
        if: github.event.inputs.branch != ''
        with:
          type: now
          from_branch: master
          target_branch: dev-${{github.event.inputs.branch}}
          github_token: ${{ github.token }}

      - name: Merge dev-${{github.event.inputs.branch}} -> prod-${{github.event.inputs.branch}}
        uses: devmasx/merge-branch@v1.3.1
        if: github.event.inputs.branch != ''
        with:
          type: now
          from_branch: dev-${{github.event.inputs.branch}}
          target_branch: prod-${{github.event.inputs.branch}}
          github_token: ${{ github.token }}